openapi: "3.0.0"
info:
  version: 1.0.0
  title: components examples
  license:
    name: MIT
paths: {}
components:
  schemas:
    Me:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        middle_name:
          description: NOT required example
          type: string
        email:
          description: nullable example
          type: string
          format: email
          nullable: true
        tag:
          type: array
          items:
            type: string
        gen:
          description: enum example
          $ref: "#/components/schemas/Generation"
        labels:
          type: object
          description: |
            for any key value pairs (dictionary)
            see: https://swagger.io/docs/specification/data-models/dictionaries/
          additionalProperties:
            type: string
      required:
        - id
        - first_name
        - last_name
        - tag
        - gen
        - labels
    Generation:
      description: 1, 2, 3, 4, 5 のいずれか
      type: string
      enum:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
