openapi: 3.1.0
info:
  title: CMC Majors
  version: v1
paths:
  /popularity:
    get:
      operationId: getPopularMajors
      summary: Get popular majors
      description: Retrieves a count of students for each declared major.
      parameters:
        - name: class
          in: query
          required: true
          schema:
            type: string
            example: "2025"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
