basePath: /
consumes:
    - application/json
definitions:
    Product:
        x-go-package: github.com/kokoichi206/go-expert/micro-intro/data
info:
    description: Documantation for Product API
    title: of Product API
    version: 1.0.0
paths:
    /products:
        get:
            description: Returns list of products
            operationId: listProducts
            responses:
                "200":
                    $ref: '#/responses/productsResponse'
produces:
    - application/json
responses:
    productsResponse:
        description: A list of products returns in the response
        schema:
            items: {}
            type: array
schemes:
    - http
swagger: "2.0"
