name: Build, Test and Deploy

on:
  push:
    branches:
      - maseter
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build:
    # HEADコミットが'skip ci'を含んでいれば、ciをキャンセルする。
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    uses: kokoichi206/count-down-timer/.github/workflows/build.yml@2ff30e9e3cd45946ced2c3c1bf3dd238d7f5d1dd

