name: golangci-lint

on:
  pull_request:
    paths:
    - 'web_app/todo/**.go'

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web_app/todo/
    steps:
      - uses: actions/checkout@v3

      - name: golang-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=./.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"


