name: test

on:
  push:
    paths:
    - 'web_app/todo/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web_app/todo/
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'

      - run: go test ./... -coverprofile=coverage.out

      - name: report coverage using octocov
        uses: k1LoW/octocov-action@v0
